ALTER TABLE questionnaire 
ADD COLUMN `attendance` bit NOT NULL AFTER `ClassID`, 
ADD COLUMN `gender` bit NOT NULL AFTER `attendance`, 
ADD COLUMN `1_module_objective` bit AFTER `gender`, 
ADD COLUMN `1_learning_material` bit AFTER `1_module_objective`, 
ADD COLUMN `1_module_content` bit AFTER `1_learning_material`, 
ADD COLUMN `1_lesson_intersting` bit AFTER `1_module_content`, 
ADD COLUMN `2_workload_length` bit NOT NULL AFTER `1_lesson_intersting`, 
ADD COLUMN `2_workload_intensity` bit NOT NULL AFTER `2_workload_length`, 
ADD COLUMN `2_workload_difficulty` bit NOT NULL AFTER `2_workload_intensity`, 
ADD COLUMN `3_module_presentation` bit NOT NULL AFTER `2_workload_difficulty`, 
ADD COLUMN `3_learning_activity` bit AFTER `3_module_presentation`, 
ADD COLUMN `3_learning_activity_outcome` bit AFTER `3_learning_activity`, 
ADD COLUMN `3_assessment_methods` bit AFTER `3_learning_activity_outcome`, 
ADD COLUMN `3_student_encouragement` bit AFTER `3_assessment_methods`, 
ADD COLUMN `3_lecturer_feedback` bit AFTER `3_student_encouragement`, 
ADD COLUMN `3_lectuer_language` bit AFTER `3_lecturer_feedback`, 
ADD COLUMN `3_lectuer_listen` bit AFTER `3_lectuer_language`, 
ADD COLUMN `3_lectuer_encourage` bit AFTER `3_lectuer_listen`,
ADD COLUMN `3_lectuer_consultation` bit AFTER `3_lectuer_encourage`;